Address missing codebook info
rstudio-education/dsbox pull request #29
Opened 2022-02-11 20:17 UTC by evandragich

This closes issue #25 ; I found the source data's original codebook and confirmed that 1 - urban, 2 - rural. This was opposite what the tutorial had, so I edited that to reflect.

2022-02-25 15:03 UTC, mine-cetinkaya-rundel requested changes
Just a few minor comments then this should be good to go!

2022-02-25 15:03 UTC, mine-cetinkaya-rundel commented on inst/tutorials/06-dcbikeshare/06-dcbikeshare.Rmd
> +Use 'case_when()' to 'mutate()' the variable and 'fct_relevel()' to convert it into a factor!
These should be back ticks not single quotes

2022-02-25 15:03 UTC, mine-cetinkaya-rundel commented on inst/tutorials/06-dcbikeshare/06-dcbikeshare.Rmd
> +First 'mutate()' the variables using 'ifelse()', then use 'fct_relevel()'
Similarly here, backticks

2022-02-25 15:03 UTC, mine-cetinkaya-rundel commented on inst/tutorials/07-exploregss/07-exploregss.Rmd
> +Remember - you'll need to remove the 'NA' values.
And backticks here too

2022-03-01 03:49 UTC, evandragich commented
@mine-cetinkaya-rundel single quotes have been amended!

2022-03-01 03:50 UTC, evandragich commented
whoops, my bad, `pr_finish()`ed on autopilot

2022-03-01 04:56 UTC, evandragich commented
Finally done!

2022-03-03 15:15 UTC, evandragich commented
> Finally done!

@mine-cetinkaya-rundel

2022-03-25 13:28 UTC, merged