Add datasets required for tutorials
rstudio-education/dsbox pull request #6
Opened 2020-08-08 18:31 UTC by lee-suddaby

Adding the necessary datasets for the tutorials due to be added to the package.

2020-08-08 18:32 UTC, lee-suddaby commented
@mine-cetinkaya-rundel

2020-08-09 09:07 UTC, mine-cetinkaya-rundel requested changes
Looking good!

Some minor edits, and then one bigger one about the foreign connected PAC datasets -- there is a way to combine documentation for a group of connected functions/datasets using the @seealso tag in Roxygen. I also wonder if some of these datasets should just be constructed at the beginning of the tutorial in the setup chunk or if they're valuable to have as separate datasets here. Once you go through the other edits, I'll do this combining/sorting through and let you know my approach.

Also, I made some edits to master while you were working on this PR as well as made some direct suggestions here. As a workflow I would recommend

- Read through comments here and accept the suggestions
- Then, in RStudio run `pr_sync()` (see the bottom of [this vignette](https://usethis.r-lib.org/articles/articles/pr-functions.html) for more on that)
- Then make changes in your PR in RStudio

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/accidents.R
> +#' We can use it to explore
I think we can remove this sentence fragment.

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/dcbikeshare.R
> +#' back at another position. Currently, there are about over 500 bike-sharing programs
What does "Currently" refer to here. Should we say "As of 2020"?

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/dcbikeshare.R
> +#' [UC Irvine](http://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset). Sources of the
```suggestion
#' [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset). Sources of the
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/dcbikeshare.R
> +#'  [dv.gov](http://dchr.dc.gov/page/holiday-schedule) for the holiday schedule.
Remove empty spaces at the beginning of lines to align with line 22

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/dcbikeshare.R
> +#' The data has been modified to better serve the goals of introductory data science education.
```suggestion
#' The data have been modified to better serve the goals of introductory data science education.
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/gss.R
> +#'   \item{advfront}{"Even if it brings no immediate benefits, scientific research that advances the frontiers of knowledge is necessary and should be supported by the federal government."}
```suggestion
#'   \item{advfront}{Response to the question "Even if it brings no immediate benefits, scientific research that advances the frontiers of knowledge is necessary and should be supported by the federal government."}
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/gss.R
> +#'   \item{advfront}{"Even if it brings no immediate benefits, scientific research that advances the frontiers of knowledge is necessary and should be supported by the federal government."}
Also say what the possible answers are, are they yes/no, or something else?

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/gss.R
> +#'   \item{harass5}{"Over the past five years, have you been harassed by your superiors or co-workers at your job, for example, have you experienced any bullying, physical or psychological abuse?"}
```suggestion
#'   \item{harass5}{Response to the question "Over the past five years, have you been harassed by your superiors or co-workers at your job, for example, have you experienced any bullying, physical or psychological abuse?"}
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/gss.R
> +#'   \item{harass5}{"Over the past five years, have you been harassed by your superiors or co-workers at your job, for example, have you experienced any bullying, physical or psychological abuse?"}
Also say what the possible answers are, are they yes/no, or something else?

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/gss.R
> +#' GSS - General Social Survey
Did we mention in the homework/tutorials which year these data are from? If so, we should add it here and make the title "Data from the XXXX General Social Survey (GSS)". If this is not mentioned somewhere let me know and I'll dig up my records and find it.

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/lego_sales.R
> +#' library(tidyverse)
Let's make this `library(dplyr)` so we're not depending on the entire tidyverse package for the package

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on DESCRIPTION
> +    tidyverse
Use `dplyr` instead of `tidyverse` here.

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/pac_2020.R
> +#' contributions from their American employees.” (source: OpenSecrets.org)
```suggestion
#' contributions from their American employees.” (Source: [OpenSecrets.org](https://www.opensecrets.org/political-action-committees-pacs/foreign-connected-pacs))
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/pac_2020.R
> +#' The data has been scraped from the OpenSecrets.org website.
Add date when these data were scraped, since they change periodically

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/pac_2020.R
> +#' Political Action Committee Contributions
```suggestion
#' Foreign-Connected PAC Contributions
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/pac_2020_raw.R
> +#' glimpse(pac_2020_raw)
```suggestion
#' pac_2020_raw
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/pac_2020_raw.R
> +#' glimpse(pac_2020_raw)
Since it's not too many columns anyway...

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/lego_sales.R
> +#' Sales of Lego sets
```suggestion
#' Sales of Lego sets (simulated)
```

2020-08-09 09:07 UTC, mine-cetinkaya-rundel commented on R/lego_sales.R
> +#' Legos in the United States.
```suggestion
#' Simulated data based on real prices for Lego sales in 2018 in the United States. 
#' Names and hobbies have been randomly generated
```

2020-08-09 18:09 UTC, lee-suddaby commented on R/dcbikeshare.R
> +#' back at another position. Currently, there are about over 500 bike-sharing programs
I took that straight from the tutorial on introds.org, so honestly I don't know.

However, a quick Google search reveals it's a lot higher than that now, so I'll change this sentence and add a year for reference.

2020-08-09 18:22 UTC, lee-suddaby commented on R/gss.R
> +#' GSS - General Social Survey
It was the 2016 GSS.

2020-08-09 18:36 UTC, lee-suddaby commented on DESCRIPTION
> +    tidyverse
@mine-cetinkaya-rundel Might be better to leave this as it, since the tutorials all use the tidyverse package.

2020-08-09 19:35 UTC, lee-suddaby commented
@mine-cetinkaya-rundel I've made those suggested changes, except for the one about removing the tidyverse dependency, which I've commented on above.

So I think all that's left to do here is to experiment with and decide on an approach for the foreign-connected PAC datasets.

2020-08-09 23:53 UTC, mine-cetinkaya-rundel commented on DESCRIPTION
> +    tidyverse
You might be right, but it seems like RStudio has a way of catching dependencies of a tutorial and prompting the user to install if needed. I'm going to try with and without in a fresh Cloud session to see what happens.

2020-08-09 23:54 UTC, mine-cetinkaya-rundel approved these changes

2020-08-09 23:54 UTC, merged